<?php
/*
*       @type           = VIEW
*
* DESCRIPTION :
* Gère les pages de type "classique" 
* -> les gages avec 1 seule liste + 1 dé
* sensuel, coquin, hot, medley, deviant... (déterminé grâce au PAGE_CODE)
*/

#-> DEFINITION DES VARIABLES GLOBALES <-#
    global $viewContent,$erreur,$limit,$vGage,$resultat;
#-> END <-#

#-> AFFICHAGE/MASQUAGE BANDEAU "ONLINE" <-#
    if(TYPE_GAGE ==1){ # Si on est en version ONLINE, afficher le bandeau spécifique
    ?>
    <div class="MenuOnline">
        VERSION ONLINE
    </div>
    <?php } 
#-> END <-#?>




<div class="levelTitle <?php echo $GLOBALS['page'.PAGE_CODE]; ?>">
<?php echo $GLOBALS['page'.PAGE_CODE]; ?><br>
</div>
<div class="wrapper" style="overflow-x:auto;">
	<div class="contenu">
	<form method="post">
			<input type="submit" class="<?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG" name="resultNb" value="<?php echo $GLOBALS['rollDice']; ?>" class="lanceur">
	</form>
	<form method="post">
			<input type="submit" name="read" value="<?php echo $GLOBALS['seeLastResult']; ?>" class="lanceur darkButton">
	</form>
	</div>


	<div class="resultat <?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG">
	<?php echo $resultat.'<br>'; ?>
	</div>

	
    <div class="marginBloc">
        Pour rappel, vous pouvez afficher la liste des gages <?php echo $GLOBALS['page'.PAGE_CODE] ?>s possibles : <button class="show"><?php echo $GLOBALS['showHide'] ?></button>
    </div>
    <p3>
        <?php #on affiche la liste des gages
        listGage($limit,$vGage); ?>
    </p3>

</div>




