<?php
/*
*       @type           = VIEW
*       @profil         = ADMINISTRATEUR
*
* DESCRIPTION :
* Permet de sélectionner un Collège pour afficher un rapport
* OU
* Permet de sélectionner un TAG pour afficher un rapport
*/

/* Définition des variables globales */
global $message,$limit,$vGage,$resultat;

if(TYPE_GAGE ==1){
?>
<div class="MenuOnline">
    VERSION ONLINE
</div>
<?php } ?>




<div class="levelTitle <?php echo $GLOBALS['page'.PAGE_CODE]; ?>">
<?php echo $GLOBALS['page'.PAGE_CODE]; ?><br>
</div>
<div class="wrapper" style="overflow-x:auto;">
	<div class="contenu">
	<form method="post">
			<input type="submit" class="<?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG" name="resultNb" value="<?php echo $GLOBALS['rollDice']; ?>" class="lanceur">
	</form>
	<form method="post">
			<input type="submit" name="read" value="<?php echo $GLOBALS['seeLastResult']; ?>" class="lanceur darkButton">
	</form>
	</div>


	<div class="resultat <?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG">
	<?php echo $resultat.'<br>'; ?>
	</div>

	
    <div class="marginBloc">
        Pour rappel, vous pouvez afficher la liste des gages <?php echo $GLOBALS['page'.PAGE_CODE] ?>s possibles : <button class="show"><?php echo $GLOBALS['showHide'] ?></button>
    </div>
    <p3>
        <?php #on affiche la liste des gages
        listGage($limit,$vGage); ?>
    </p3>

</div>




