<?php
/*
*       @type           = VIEW
*       @profil         = ADMINISTRATEUR
*
* DESCRIPTION :
* Gère les pages de type "DoublePlayer" 
* -> les gages avec 2 listes + 1 dé pour chaque joueur
* jeu de 21, illustré... (déterminé grâce au PAGE_CODE)
*/

#-> DEFINITION DES VARIABLES GLOBALES <-#
    global $viewContent,$erreur,$lastPlayer,$resultat_to_show,$resultat_URL,$count1,$count2,$choix1,$choix2,$limite_list,$levelGage;
#-> END <-#

#-> AFFICHAGE/MASQUAGE BANDEAU "ONLINE" <-#
    if(TYPE_GAGE ==1){ # Si on est en version ONLINE, afficher le bandeau spécifique
    ?>
    <div class="MenuOnline">
        VERSION ONLINE
    </div>
    <?php } 
#-> END <-#?>



<div class="levelTitle <?php echo $GLOBALS['page'.PAGE_CODE]; ?>">
    <?php echo $GLOBALS['list'].' '.$GLOBALS['page'.PAGE_CODE]; ?><br>
</div>

<div class="wrapper" style="overflow-x:auto;">
<?php if (PAGE_CODE==9){ ?>
    <!-- gages illustrés -->
	<div class="blocText">
        <p>
            La version illustrée est, comme son nom l'indique, une liste de gages illustrés chacun en image. Il n'y a qu'à reproduire ce qu'elles montrent.
        </p>
        <p>
            Ici, les gages sont spécifiques Homme et Femme. Il faudra donc lancer le dé correspondant à l'un de ces 2 types de gages.
        </p>
	</div>
<?php } ?>
<?php if (PAGE_CODE==10){ ?>
    <!-- jeu du 21 -->
	<div class="blocText">
	Le jeu du 21 est très simple : 1 lancé de 2 dés à 6 faces. <br>
	A chaque lancé, on additionne les résultats des 2 dés, qu'on ajoute au résultat précédant (compteur). <br>
	Le but est d'arriver en premier à 21 EXACTEMENT.</br>
	Si la somme des 2 dés lancés, additionnée au résultat du compteur, dépasse 21, alors cette somme est soustraite. Si ça ne dépasse pas 21, alors c'est ajouté. Et vis et versa.</br>
	Essayez, vous verrez !
	</div>
<?php } ?>
	<div class="contenu">
       <?php if(TYPE_PLAY >0){ #si version classique ?>
        <p>
            Cette liste comportant plusieurs niveaux d'intensité, sélectionnez ci-dessous celui de votre choix.
        </p>     
        
        <?php if(TYPE_GAGE ==0){ #si version classique ?>
        <form method="post">
           <select name="levelgage">
                <option value="1"<?php if($levelGage == 1) { echo "selected" ; }?>>sensuel</option>
                <option value="2" <?php if($levelGage == 2) { echo "selected" ; }?>>érotique</option> 
                <option value="3" <?php if($levelGage == 3) { echo "selected" ; }?>>déviant</option>  
            </select>
            <input type="submit" value="<?php echo $GLOBALS['choose']; ?>" name="chooselvl" class="darkButton">
        </form>
        <?php } ?>
        
        <!-- selecteur de niveau -->
	    <?php if(TYPE_GAGE ==1){ #si version Online ?>
        
        <form method="post">
           <select name="levelgage">
                <option value="1"<?php if($levelGage == 1) { echo "selected" ; }?>>sensuel</option>
                <option value="2" <?php if($levelGage == 2) { echo "selected" ; }?>>érotique</option>  
            </select>
            <input type="submit" value="<?php echo $GLOBALS['choose']; ?>" name="chooselvl" class="darkButton">
        </form>
        <?php
           } 
         }?>

        <!-- effacer les compteurs -->
        <form method="post">
                <input type="submit" class="darkButton" name="erase" value="<?php echo $GLOBALS['erase']; ?>" class="lanceur">
        </form>

        <!-- COMPTEURS -->
        <table>
            <tr>
                <!-- Surligne le dernier player -->
                <td <?php if($lastPlayer==1){echo'class="tdFocus"';}else{ echo 'class="tdShowGirl"';} ?>>
                    <?php echo $GLOBALS['player1']; ?>
                </td>
                <!-- Surligne le dernier player -->
                <td <?php if($lastPlayer==2){echo'class="tdFocus"';}else{ echo 'class="tdShowBoy"';} ?>>
                    <?php echo $GLOBALS['player2']; ?>
                </td>
            </tr>
            <tr>
                <td class="tdNeutral">
                    <form method="post" action="#result">
                            <input type="submit" name="player1" value="<?php echo $GLOBALS['rollDice']; ?>" <?php if($lastPlayer==1 || $count1==21 || $count2==21){echo'disabled class="disabledBtn lanceur"';}else{echo'class="'.$GLOBALS['page'.PAGE_CODE].'Btn lanceur"';} ?> >
                    </form>
                </td>
                <td class="tdNeutral">
                    <form method="post" action="#result">
                            <input type="submit" name="player2" value="<?php echo $GLOBALS['rollDice']; ?>" <?php if($lastPlayer==2 || $count2==21 || $count1==21){echo'disabled class="disabledBtn lanceur"';}else{echo'class="'.$GLOBALS['page'.PAGE_CODE].'Btn lanceur"';} ?> >
                    </form>
                </td>
            </tr>
            <tr>
                <td class=" CellinfoSmall"> <!-- result for P1 -->
                    <?php echo $GLOBALS['resultFor'].' '.$GLOBALS['player1']; ?>
                </td>
                <td class=" CellinfoSmall"><!-- result for P2 -->
                    <?php echo $GLOBALS['resultFor'].' '.$GLOBALS['player2']; ?>
                </td>
            </tr>
            <tr>
                <td class="tdShowGirl">
                    <?php echo $count1; ?>
                </td>
                <td class="tdShowBoy">
                    <?php echo $count2; ?>
                </td>
            </tr>
        </table>
	</div>

    <!-- RESULTAT -->
	<div id="result" class="resultat <?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG">
		<?php 
        if(TYPE_PLAY == 0){ # si c'est jeu de dé
            echo $resultat_to_show;
            
            if(isset($_POST['player1']) OR isset($_POST['player2'])){
                echo '<br><font class="resultSecondary">(1er Dé : '.$choix1.' | 2nd Dé : '.$choix2.')</font><br>';
            }
            if($count1==21){
                echo '<div class="tdShowGirl">'.$GLOBALS['player1'].' '.$GLOBALS['win'].' !</div>';
            }
            if($count2==21){
                echo '<div class="tdShowBoy">'.$GLOBALS['player2'].' '.$GLOBALS['win'].' ! !</div>';
            }                
        }
        if(TYPE_PLAY == 1){ # si c'est gage illustré
            echo '<img src="'.$resultat_URL.'" class="illuResultGage">';
        }
         ?>    
	</div>
	<?php 
        if(TYPE_PLAY == 1){ # si c'est jeu gages illustrés?>
            <div class="marginBloc">
                Pour rappel, vous pouvez afficher la liste des gages possibles : <button class="show"><?php echo $GLOBALS['showHide'] ?></button>
            </div>
            <p3>
               <div id="dehide_contenu">
                    <table>
                    <?php #on affiche la liste des gages
                    doubleListe($GLOBALS['liste_player1'],$GLOBALS['liste_player2'],$GLOBALS['total_gage']); 
                    ?>

                    </table>
                    <a class="show" href="#hide_contenu">Retour haut</a>
                </div>     
            </p3>
        <?php } ?>

</div>



