<?php
/*
*       @type           = VIEW
*       @profil         = ADMINISTRATEUR
*
* DESCRIPTION :
* Gère les pages de type "DoublePlayer" 
* -> les gages avec 2 listes + 1 dé pour chaque joueur
* jeu de 21, illustré... (déterminé grâce au PAGE_CODE)
*/

#-> DEFINITION DES VARIABLES GLOBALES <-#
    global $viewContent,$erreur,$lastPlayer,$resultat_to_show,$resultat_URL,$count1,$count2,$choix1,$choix2,$limite_list,$levelGage;
#-> END <-#

#-> AFFICHAGE/MASQUAGE BANDEAU "ONLINE" <-#
    if(TYPE_GAGE ==1){ # Si on est en version ONLINE, afficher le bandeau spécifique
    ?>
    <div class="MenuOnline">
        VERSION ONLINE
    </div>
    <?php } 
#-> END <-#?>



<div class="levelTitle <?php echo $GLOBALS['page'.PAGE_CODE]; ?>">
<?php echo $GLOBALS['page'.PAGE_CODE]; ?><br>
</div>

<div class="wrapper" style="overflow-x:auto;">
<?php if (PAGE_CODE==9){ ?>
    <!-- gages illustrés -->
	<div class="blocText">
	La version illustrée est, comme son nom l'indique, une liste de gages illustrés chacun en image. Il n'y a qu'à reproduire ce qu'elle montre.<br>
	Ici, les gages sont spécifiques Homme et Femme. Il faudra donc lancer le dé correspondant à l'un de ces 2 types de gages.<br>
	Pour utiliser ces gages en version 'medley', vous pourrez retrouver les 'coordonées' des gages en affichant la liste. Les gages femme ayant F+N°, les gages homme M+N°.
	</div>
<?php } ?>
<?php if (PAGE_CODE==10){ ?>
    <!-- jeu du 21 -->
	<div class="blocText">
	Le jeu du 21 est très simple : 1 lancé de 2 dés à 6 faces. <br>
	A chaque lancé, on additionne les résultats des 2 dés, qu'on ajoute au résultat précédant (compteur). <br>
	Le but est d'arriver en premier à 21 EXACTEMENT.</br>
	Si la somme des 2 dés lancés, additionnée au résultat du compteur, dépasse 21, alors cette somme est soustraite. Si ça ne dépasse pas 21, alors c'est ajouté. Et vis et versa.</br>
	Essayez, vous verrez !
	</div>
<?php } ?>
	<div class="contenu">
	    <!-- selecteur de niveau -->
	    <?php if(TYPE_GAGE ==1){ #si version Online ?>
        <form method="post">
           <select name="levelgage">
                <option value="1"<?php if($levelGage == 1) { echo "selected" ; }?>>sensuel</option>
                <option value="2" <?php if($levelGage == 2) { echo "selected" ; }?>>érotique</option>  
            </select>
            <input type="submit" value="<?php echo $GLOBALS['choose']; ?>" name="chooselvl">
        </form>
        <?php } ?>

        <!-- effacer les compteurs -->
        <form method="post">
                <input type="submit" class="<?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG" name="erase" value="<?php echo $GLOBALS['erase']; ?>" class="lanceur">
        </form>

        <!-- COMPTEURS -->
        <table>
            <tr>
                <td class="tdNeutral">
                    <!-- Surligne le dernier player -->
                    <?php if($lastPlayer==1){echo'<font class="colorBlanc tdFocus">ELLE</font>';}
                    else{ echo 'ELLE';}
                    ?>
                </td>
                <td class="tdNeutral">
                <!-- Surligne le dernier player -->
                    <?php if($lastPlayer==2){echo'<font class="colorBlanc tdFocus">LUI</font>';}
                    else{ echo 'LUI';}
                    ?>
                </td>
            </tr>
            <tr>
                <td class="tdNeutral">
                    <form method="post" action="#result">
                            <input type="submit" class="<?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG" name="player1" value="<?php echo $GLOBALS['rollDice']; ?>" class="lanceur">
                    </form>
                </td>
                <td class="tdNeutral">
                    <form method="post" action="#result">
                            <input type="submit" class="<?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG" name="player2" value="<?php echo $GLOBALS['rollDice']; ?>" class="lanceur">
                    </form>
                </td>
            </tr>
            <tr>
                <td class=" CellinfoSmall">
                    Résultat pour ELLE
                </td>
                <td class=" CellinfoSmall">
                    Résultat pour LUI
                </td>
            </tr>
            <tr>
                <td class="tdNeutral">
                    <?php echo $count1; ?>
                </td>
                <td class="tdNeutral">
                    <?php echo $count2; ?>
                </td>
            </tr>
        </table>
	</div>

    <!-- RESULTAT -->
	<div id="result" class="resultat <?php echo $GLOBALS['page'.PAGE_CODE]; ?>BG">
		<?php 
        if(TYPE_PLAY == 0){ # si c'est jeu de dé
            echo $resultat_to_show;
            
            if(isset($_POST['player1']) OR isset($_POST['player2'])){
                echo '<br><font class="resultSecondary">(1er Dé : '.$choix1.' | 2nd Dé : '.$choix2.')</font><br>';
            }
            if($count1==21){
                echo 'JOUEUR 1 GAGNE !<br>';
            }
            if($count2==21){
                echo 'JOUEUR 2 GAGNE !';
            }                
        }
        if(TYPE_PLAY == 1){ # si c'est gage illustré
            echo '<img src="'.$resultat_URL.'" class="illuResultGage">';
        }
         ?>    
	</div>
	<?php 
        if(TYPE_PLAY == 1){ # si c'est jeu gages illustrés?>
            <div class="marginBloc">
                Pour rappel, vous pouvez afficher la liste des gages <?php echo $GLOBALS['page'.PAGE_CODE] ?>s possibles : <button class="show"><?php echo $GLOBALS['showHide'] ?></button>
            </div>
            <p3>
               <div id="dehide_contenu">
                    <table>
                    <?php #on affiche la liste des gages
                    doubleListe($GLOBALS['liste_player1'],$GLOBALS['liste_player2'],$GLOBALS['total_gage']); 
                    ?>

                    </table>
                    <a class="show" href="#hide_contenu">Retour haut</a>
                </div>     
            </p3>
        <?php } ?>

</div>



