<?php 

/**
Index général.
Si l'utilisateur arrive sur cette page, c'est qu'il n'est pas authentifé.
Ce Module VIEW INDEX est donc vide, car le formulaire de connexion apparaît dans le Module AUTH LOGIN

**/

if(TYPE_GAGE ==1){
?>
<div class="MenuOnline">
    VERSION ONLINE
</div>
<?php } ?>

<div class="wrapper" style="overflow-x:auto;">
<h1>Bienvenu sur le jeu de gages coquins</h1>
	<div class="blocText">
    <?php if(TYPE_GAGE == 1){ ?>
	    <p>
		Voici un petit module de choix aléatoire de gages, parmi une liste prédéfinie spécialement adaptée au jeu à distance.<br>
		Suivant le même principe que la "version classique", en fonction du niveau d'intensité que vous souhaitez jouer, cliquez dans le menu en haut.<br>
		Suivant le niveau sélectionné, les gages seront plus ou moins osés, allant du sensuel soft à l'osé très franc.
		<br>
		Bon jeu.
        </p>
    <?php }
        if(TYPE_GAGE == 0){ ?>
		<p>
        Voici un petit module de choix aléatoire de gages coquins, parmi des listes prédéfinies.<br>
		Suivant le niveau d'intensité (la version) que vous souhaitez jouer, cliquez dans le menu en haut.<br>
		En fonction de la version, les gages seront plus ou moins osés, allant du sensuel soft à l'osé très franc.
		</p>
		<p>
		Si vous avez accès au <i><a href="gage?codepage=4&typegage=0&typepage=2" class="<?php echo $GLOBALS['page4']; ?>">Tableau des supplices</a></i>, vous pouvez alors utiliser le module spécifique prévu à cet effet.<br>
		-> + d'info sur le module <a href="gage?codepage=4&typegage=0&typepage=2" class="<?php echo $GLOBALS['page4']; ?>"><?php echo $GLOBALS['page4']; ?> </a></a>
		</p>
		
		<p>
		Enfin Si vous êtes loin de votre partenaire, vous pouvez utiliser la <a href="<?php echo $GLOBALS['page0']; ?>?typeplay=1" class="<?php echo $GLOBALS['page0']; ?>"><?php echo $GLOBALS['online']; ?> </a> avec des gages spéciaux "longue distance".<br>
		</p>
    <?php } ?>
		Des questions ? Des remarques ? Vous souhaitez compléter/modifier/ajouter un niveau de gage ?<br>
		N'hésitez pas à contacter le développeur (lien direct en bas de page)
	</div>
	<div class="cellCenter"><img src="<?php echo PATH_IMG;?>/logo.png" alt="" class="logo"></div>
</div>
<?php
    

//src="../application/library/images/logo.png"
