<?php 

/**
Index général.
Si l'utilisateur arrive sur cette page, c'est qu'il n'est pas authentifé.
Ce Module VIEW INDEX est donc vide, car le formulaire de connexion apparaît dans le Module AUTH LOGIN

**/

#-> AFFICHAGE/MASQUAGE BANDEAU "ONLINE" <-#
    if(TYPE_GAGE ==1){ # Si on est en version ONLINE, afficher le bandeau spécifique
    ?>
    <div class="MenuOnline">
        VERSION ONLINE
    </div>
    <?php } 
#-> END <-#?>

<div class="wrapper" style="overflow-x:auto;">
<h1><?php echo $GLOBALS['philoNa']; ?></h1>
	<div class="logBg">
		<div class="log">
			La philosophie Na est inspirée du peuple chinois éponyme (ethnologiquement connu sous le nom de <a href="https://fr.wikipedia.org/wiki/Moso" target="_blank">"peuple Moso"</a>).
			<br>
			C'est avant tout l'esprit "sans tabou" et leur rapport amoureux libres qui sont retenus (<a href="http://edit-biog.over-blog.com/article-35165208.html" target="_blank">en savoir +</a>).

			<br><br>
			Partant de ce postulat, un Na est quelqu'un d'hédoniste qui cherche à faire de l'existence humaine un plaisir, ne s'en refusant donc aucun pourvu qu'il n'entrave pas celui de quelqu'un d'autre.
			<br>
			Au contraire, le Na cherchera même plutôt le plaisir partagé, car le partage du plaisir est déjà la base du plaisir Na.

			<br><br>
			C'est donc tout naturellement que cette petite application de gages érotiques se targue d'être l'outil idéal à tout Na qui s'assume et souhaite varier un peu les plaisirs de sa vie sexuelle.

			<br><br><br>

			<h3>Quelques sloggans Na</h3>
			<ul>
			<li>Pratique et modulable</li>
			<li>On ne néglige pas le plaisir</li>
			<li>Ivre de désir et d'envie pour le plaisir d’autrui</li>
			<li>Cultiver la vivacité de corps et d'esprit </li>
			</ul>
		</div>
	</div>
</div>
<?php
    


