

<div class="footer">
<!-- <a href="page.php"> -->
<a href="mailto:yoa@hmamail.com?subject=[JGC] - Message depuis le site"><?php echo 'Contacter le développeur'; ?> </a> | 
    <a href="index?typepage=3&codepage=11"><?php echo $GLOBALS['philoNa']; ?> </a> | 
    <a href="index?typepage=3&codepage=12"><?php echo $GLOBALS['page12']; ?> </a> | <a href="http://sulfehn.free.fr/yoalad" target="_blank">© <?php echo $GLOBALS['creator']; ?></a>  <?php echo date(Y); ?>
</div>